networks:
  app_net:
     external: true 

services:
  nats:
    image: nats:alpine
    container_name: nats
    restart: always
    command: -c /etc/nats/nats.conf
    ports:
      - "4222:4222" # client port
      - "6222:6222" # cluster port
      - "8222:8222" # monitoring port
    volumes:
      - ./nats.conf:/etc/nats/nats.conf
      - $JETSTREAM_STORAGE:/data
    networks:
      - app_net

  surveyor:
    image: natsio/nats-surveyor
    container_name: nats-surveyor
    restart: always
    volumes:
      - ./observations:/observations
      - $JETSTREAM_STORAGE:/data
    command: |
      -s "${NATS_SURVEYOR_SERVERS}" --accounts --observe /observations --jetstream /data
    networks:
      - app_net
    labels:
      org.label-schema.group: "nats-monitoring"
    depends_on:
      - nats
