version: '3.5'
services:
  zookeeper:
    image: zookeeper:3.6
    container_name: zookeeper
    hostname: zookeeper
    restart: always
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.10
    volumes:
      - ${PWD}/zookeeper/datalog:/datalog
      - ${PWD}/zookeeper/data:/data
      - ${PWD}/zookeeper/log:/log
      - ${PWD}/zookeeper/logs:/logs
  clickhouse01:
    image: clickhouse/clickhouse-server
    container_name: clickhouse01
    hostname: clickhouse01
    restart: always
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.11
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
    volumes:
      - ${PWD}/clickhouse01/etc:/etc/clickhouse-server
      - ${PWD}/clickhouse01/data:/var/lib/clickhouse/
      - ${PWD}/clickhouse01/log:/var/log/clickhouse-server/
    depends_on:
      - zookeeper
  clickhouse02:
    image: clickhouse/clickhouse-server
    container_name: clickhouse02
    hostname: clickhouse02
    restart: always
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.12
    ports:
      - "127.0.0.1:8124:8123"
      - "127.0.0.1:9001:9000"
    volumes:
      - ${PWD}/clickhouse02/etc:/etc/clickhouse-server
      - ${PWD}/clickhouse02/data:/var/lib/clickhouse/
      - ${PWD}/clickhouse02/log:/var/log/clickhouse-server/
    depends_on:
      - zookeeper
  clickhouse03:
    image: clickhouse/clickhouse-server
    container_name: clickhouse03
    hostname: clickhouse03
    restart: always
    networks:
      clickhouse-network:
        ipv4_address: 172.23.0.13
    ports:
      - "127.0.0.1:8125:8123"
      - "127.0.0.1:9002:9000"
    volumes:
      - ${PWD}/clickhouse03/etc:/etc/clickhouse-server
      - ${PWD}/clickhouse03/data:/var/lib/clickhouse/
      - ${PWD}/clickhouse03/log:/var/log/clickhouse-server/
    depends_on:
      - zookeeper

networks:
  clickhouse-network:
    name: clickhouse-network
    ipam:
      config:
        - subnet: 172.23.0.0/24
