services:
  subconverter:
    container_name: subconverter
    image: tindy2013/subconverter:latest
    restart: unless-stopped
    ports:
      - '25500:25500'

  as:
    image: stilleshan/sub
    container_name: sub
    ports:
      - 18080:80
    volumes:
      - ./conf:/usr/share/nginx/html/conf
    restart: always