version: '3.8'
services:
  clickhouse:
    image: 'clickhouse/clickhouse-server:${CHVER}'
    user: '101:101'
    container_name: clickhouse
    hostname: clickhouse
    volumes:
      - ${PWD}/config.xml:/etc/clickhouse-server/config.d/config.xml
      - ${PWD}/users.xml:/etc/clickhouse-server/users.d/users.xml
      - ${PWD}/log:/var/log/clickhouse-server/
      - ${PWD}/data:/var/lib/clickhouse/
    ports:
      - '127.0.0.1:8123:8123'
      - '127.0.0.1:9000:9000'
    depends_on:
      - clickhouse-keeper
  clickhouse-keeper:
    image: 'clickhouse/clickhouse-keeper:${CHKVER}'
    user: '101:101'
    container_name: clickhouse-keeper
    hostname: clickhouse-keeper
    volumes:
      - ${PWD}/keeper_config.xml:/etc/clickhouse-keeper/keeper_config.xml
      - ${PWD}/log:/var/log/clickhouse-keeper/
      - ${PWD}/data:/var/lib/clickhouse-keeper/
    ports:
      - '127.0.0.1:9181:9181'
