version: "3.3"
services:
  gitlab-ce:
    image: gitlab/gitlab-ee:14.7.3-ee.0
    container_name: gitlab-ee
    restart: always
    ports:
      - "8443:443"
      - "8080:80"
      - "822:822"
    volumes:
      - ./etc:/etc/gitlab
      - ./log:/var/log/gitlab
      - ./data:/var/opt/gitlab
      - ./license_key.pub:/opt/gitlab/embedded/service/gitlab-rails/.license_encryption_key.pub
      - ./ULTIMATE_PLAN_license.rb:/opt/gitlab/embedded/service/gitlab-rails/ee/app/models/license.rb
    networks:
      - app

  kroki:
    image: yuzutech/kroki
    container_name: kroki
    restart: always
    depends_on:
      - blockdiag
      - mermaid
#      - bpmn
      - excalidraw
    environment:
      - KROKI_BLOCKDIAG_HOST=blockdiag
      - KROKI_MERMAID_HOST=mermaid
#      - KROKI_BPMN_HOST=bpmn
      - KROKI_EXCALIDRAW_HOST=excalidraw
    networks:
      - app

  blockdiag:
    image: yuzutech/kroki-blockdiag
    restart: always
    networks:
      - app

  mermaid:
    image: yuzutech/kroki-mermaid
    restart: always
    networks:
      - app

#  bpmn:
#    image: yuzutech/kroki-bpmn
#    restart: always
#    networks:
#      - app

  excalidraw:
    image: yuzutech/kroki-excalidraw
    restart: always
    networks:
      - app

networks:
  app:
    external: true
