version: '3.8'
services:

  mongodb:
    image: mongo:6-jammy
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - ${PWD}/data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
