
services:
  mongodb:
    image: arm64v8/mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - ${PWD}/data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
