services:
  drone-runner:
    image: drone/drone-runner-docker:1
    environment:
      - DRONE_RPC_HOST=drone.topzoneweb.cn
      - DRONE_RPC_PROTO=https
      - DRONE_RPC_SECRET=10f5aa6cd83b3bafde057d3ef7fa5156
      - DRONE_RUNNER_NAME=tx_cloud_arm64
      - DRONE_RUNNER_CAPACITY=10
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
