version: "3"

services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: "${ZO_ROOT_USER_EMAIL}"
      ZO_ROOT_USER_PASSWORD: "${ZO_ROOT_USER_PASSWORD}"
    ports:
      - "5080:5080"
    volumes:
      - ${PWD}/data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

