version: "3"

services:
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    restart: unless-stopped
    environment:
      ZO_ROOT_USER_EMAIL: "hengheng8848@gmail.com"
      ZO_ROOT_USER_PASSWORD: "23J750r4HZxjX1me8k69"
    ports:
      - "5080:5080"
    volumes:
      - ${PWD}/data:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

