services:
  mysql:
    image: arm64v8/mysql:9
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
    volumes:
      - '${PWD}/data/db:/var/lib/mysql'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
        - app_net

networks:
  app_net:
    external: true
