services:
  semaphore:
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    environment:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN_PASSWORD: 123
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
    volumes:
      - ./data/home:/etc/semaphore # config.json location
      - ./data/lib:/var/lib/semaphore # database.boltdb location (Not required if using mysql or postgres)
    networks:
      - app_net

networks:
  app_net:
    external: true
